language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"


script:
  - pwd
  - ls -l 
  - docker --version # print the version for logging
  - docker build -f ./udagram-api-feed/Dockerfile -t udagram-api-feed ./udagram-api-feed
  - docker images
  - docker tag udagram-api-feed fr77/udagram-api-feed:latest
  - docker build -f ./udagram-api-user/Dockerfile -t udagram-api-feed ./udagram-api-user
  - docker images
  - docker tag udagram-api-user fr77/udagram-api-user:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fr77/udagram-api-feed
  - docker push fr77/udagram-api-user
