language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"




script:
  - pwd
  - ls -l 
  - docker --version # print the version for logging
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f ./udagram-api-feed/Dockerfile -t udagram-api-feed ./udagram-api-feed
  - docker images
  - docker tag udagram-api-feed fr77/udagram-api-feed:latest
  - docker build -f ./udagram-api-user/Dockerfile -t udagram-api-user ./udagram-api-user
  - docker images
  - docker tag udagram-api-user fr77/udagram-api-user:latest
  - docker build -f ./udagram-frontend/Dockerfile -t udagram-frontend ./udagram-frontend
  - docker images
  - docker tag udagram-frontend fr77/udagram-frontend:latest
  - docker build -f ./udagram-reverse-proxy/Dockerfile -t udagram-reverse-proxy ./udagram-reverse-proxy
  - docker images
  - docker tag udagram-reverse-proxy fr77/udagram-reverse-proxy:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fr77/udagram-api-feed
  - docker push fr77/udagram-api-user
  - docker push fr77/udagram-frontend
  - docker push fr77/udagram-reverse-proxy
