apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-user
  name: udagram-api-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-api-feed
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: udagram-api-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}